name = "matcha-jump-api"
main = "src/index.js"
compatibility_date = "2025-06-04"

# Environment variables
[vars]
BASE_RPC_URL = "https://mainnet.base.org"
PAYMENT_ADDRESS = "0x0db12C0A67bc5B8942ea3126a465d7a0b23126C7"
HYPE_TOKEN_ADDRESS = "0x85225Ed797fd4128Ac45A992C46eA4681a7A15dA"
QUICK_AUTH_DOMAIN = "matcha-jump.kasra.codes"
NODE_ENV = "production"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "matcha-jump-db"
database_id = "ad02cf01-57a3-4a37-a8f7-5ad35ec0e45c"

# Secrets (to be set via wrangler secret)
# wrangler secret put JWT_SECRET
